layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: false
    projects:
      - osbudget-ionic
      - GattaHomes
      - personal-website

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: eric-froese-58a30811a
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: EricFroese4
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Elixir
    web_url: https://github.com/elixir-lang/elixir
    image_url: https://discourse-user-assets.s3.amazonaws.com/original/2X/f/ffb29c7c694656265e093920b571731fb25b6029.png

  - name: Phoenix Framework
    web_url: https://github.com/phoenixframework/phoenix
    image_url: https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/254_Phoenix_Framework_logo-512.png

  - name: Ember.js
    web_url: https://github.com/emberjs/ember.js
    image_url: https://emberjs.com/images/brand/ember_Tomster-Lockup.png

  - name: Svelte
    web_url: https://github.com/sveltejs/svelte
    image_url: https://svelte.dev/svelte-logo-outline.svg
